/**
 * Export Manager
 * Handles JSON, PNG, and PDF exports
 */
class ExportManager {
  constructor(state, eventBus, canvasManager) {
    this.state = state;
    this.eventBus = eventBus;
    this.canvasManager = canvasManager;
  }

  /**
   * Export as JSON
   */
  exportJSON() {
    const state = this.state.getState();
    
    const exportData = {
      version: '1.0.0',
      exported: new Date().toISOString(),
      metadata: state.metadata,
      floorPlan: state.floorPlan,
      items: state.items.map(item => ({
        id: item.id,
        itemId: item.itemId,
        label: item.label,
        lengthFt: item.lengthFt,
        widthFt: item.widthFt,
        x: item.x,
        y: item.y,
        angle: item.angle,
        locked: item.locked,
        category: item.category,
        color: item.color
      })),
      settings: state.settings
    };

    const json = JSON.stringify(exportData, null, 2);
    const filename = `${state.metadata.projectName || 'layout'}-${Date.now()}.json`;
    
    Helpers.downloadFile(json, filename, 'application/json');
    this.eventBus.emit('export:json:complete', filename);
    
    return exportData;
  }

  /**
   * Export as PNG
   */
  exportPNG(resolution = 1) {
    const dataURL = this.canvasManager.toDataURL({
      multiplier: resolution,
      format: 'png',
      quality: 1
    });

    const filename = `${this.state.get('metadata.projectName') || 'layout'}-${resolution}x.png`;
    
    // Download
    const link = document.createElement('a');
    link.href = dataURL;
    link.download = filename;
    link.click();

    this.eventBus.emit('export:png:complete', { filename, resolution });
    
    return dataURL;
  }

  /**
   * Export as PDF
   */
  async exportPDF(options = {}) {
    if (typeof jsPDF === 'undefined') {
      console.error('jsPDF library not loaded');
      return;
    }

    // Get canvas image
    const imgData = this.canvasManager.toDataURL({
      multiplier: 2,
      format: 'png'
    });

    // Create PDF
    const pdf = new jsPDF({
      orientation: options.orientation || 'landscape',
      unit: 'in',
      format: options.format || 'letter'
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = Config.PDF_MARGINS;

    // Header
    pdf.setFontSize(18);
    pdf.setFont(undefined, 'bold');
    pdf.text(this.state.get('metadata.projectName') || 'Garage Layout', margin, margin + 0.3);

    pdf.setFontSize(10);
    pdf.setFont(undefined, 'normal');
    const clientName = this.state.get('metadata.clientName');
    if (clientName) {
      pdf.text(`Client: ${clientName}`, margin, margin + 0.6);
    }
    pdf.text(`Date: ${new Date().toLocaleDateString()}`, margin, margin + 0.9);

    // Canvas image
    const imgWidth = pageWidth - margin * 2;
    const imgHeight = imgWidth * 0.6; // Maintain aspect ratio
    const imgY = margin + 1.2;

    pdf.addImage(imgData, 'PNG', margin, imgY, imgWidth, imgHeight);

    // Floor plan info
    let textY = imgY + imgHeight + 0.3;
    const floorPlan = this.state.get('floorPlan');
    
    if (floorPlan) {
      pdf.setFontSize(12);
      pdf.setFont(undefined, 'bold');
      pdf.text('Floor Plan Specifications:', margin, textY);
      
      pdf.setFontSize(10);
      pdf.setFont(undefined, 'normal');
      textY += 0.25;
      pdf.text(`Dimensions: ${floorPlan.widthFt}' × ${floorPlan.heightFt}'`, margin, textY);
      textY += 0.2;
      pdf.text(`Area: ${floorPlan.area} sq ft`, margin, textY);
      textY += 0.2;
      
      const occupancy = this.calculateOccupancy();
      pdf.text(`Occupied: ${occupancy.toFixed(1)}%`, margin, textY);
    }

    // Item list
    textY += 0.4;
    const items = this.state.get('items') || [];
    
    if (items.length > 0) {
      pdf.setFontSize(12);
      pdf.setFont(undefined, 'bold');
      pdf.text('Items:', margin, textY);
      
      pdf.setFontSize(9);
      pdf.setFont(undefined, 'normal');
      textY += 0.25;

      items.forEach((item, index) => {
        if (textY > pageHeight - margin - 0.5) {
          pdf.addPage();
          textY = margin;
        }
        
        const itemText = `${index + 1}. ${item.label} - ${item.lengthFt}' × ${item.widthFt}'`;
        pdf.text(itemText, margin + 0.2, textY);
        textY += 0.18;
      });
    }

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(150);
    pdf.text('Generated by Garage Layout Planner', margin, pageHeight - margin / 2);

    // Save
    const filename = `${this.state.get('metadata.projectName') || 'layout'}.pdf`;
    pdf.save(filename);

    this.eventBus.emit('export:pdf:complete', filename);
    
    return pdf;
  }

  /**
   * Calculate occupancy percentage
   */
  calculateOccupancy() {
    const floorPlan = this.state.get('floorPlan');
    if (!floorPlan) return 0;

    const totalArea = floorPlan.widthFt * floorPlan.heightFt;
    const items = this.state.get('items') || [];
    const occupiedArea = items.reduce((sum, item) => sum + (item.lengthFt * item.widthFt), 0);

    return (occupiedArea / totalArea) * 100;
  }

  /**
   * Generate thumbnail
   */
  generateThumbnail(width = 200, height = 150) {
    return this.canvasManager.toDataURL({
      multiplier: 1,
      format: 'png',
      width: width,
      height: height
    });
  }
}

// Make available globally
if (typeof window !== 'undefined') {
  window.ExportManager = ExportManager;
}
